### ISSUE TITLE
Implementar lógica para silenciar el bot en la noche

### ISSUE THREAD

**Issue by ur13l** [ur13l/promo-bot-mx-lambda#2]
La función lambda es ejecutada durante las 24 horas del día, cada veinte minutos, lo cual da el problema de que se envían notificaciones toda la noche. Sugiero que el bot tenga considerado un horario definido, de forma que las publicaciones que se hagan en horarios nocturnos se almacenen y sean enviadas de manera paulatina hasta el día siguiente. Esto implicaría la creación de otra función lambda y de alguna lógica que ponga en cola los mensajes pendientes hasta la mañana.

**Comment by leonardlib** [comment]
@ur13l esta parte quedamos en que cada usuario puede personalizar las notificaciones del chat en Telegram, ¿verdad?

**Comment by ur13l** [comment]
Hmm... pues creo que no la vamos a hacer funcionalidad al final del día.
